-- 测试 SQL 文件
CREATE DATABASE IF NOT EXISTS ${DB_NAME};
USE ${DB_NAME};

CREATE TABLE ${TABLE_NAME} (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(${NAME_LENGTH}) NOT NULL,
    email VARCHAR(255),
    created_by VARCHAR(50) DEFAULT '${CREATED_BY}',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO ${TABLE_NAME} (name, email, created_by)
VALUES ('${DEFAULT_USER}', '${ADMIN_EMAIL}', 'system');
